### PR TITLE
Added unchecking a selected checkbox

### PR DESCRIPTION
**Pull request by nicoecheza**
Hey, the unchecking feature was not working fine, I added one line to fix it. 

Regards

### CODE REVIEW

**Comment by ziad-saab** [comment]
@nicoecheza can you please provide a use-case where this was not working as expected before your PR?

**Comment by nicoecheza** [comment]
Sure. 
1. We have a checkbox which "selects all" / "unselects all" the checkboxes. 
2. The value prop for the CheckboxGroup component is defined in state as "categories". 
3. Click on "select all" => it updates the categories state with all the categories and selects all the checkboxes
4. Click again to unselect all, it updates the state, the state gets passed fine to CheckboxGroup as an empty array, but since the method "setCheckedBoxes" selects the checkboxes that "destinationValue" has (destinationValue.indexOf($checkbox.value) >= 0) and checks the ones found, but doesn't uncheck the ones not found, this is not working.

**Comment by ziad-saab** [comment]
:shipit:

**Comment by ziad-saab** [comment]
@nicoecheza version `0.2.1` includes your fix.

**Pull request merged**
