### PR TITLE
Add checked attribute

### PR DESCRIPTION
**Pull request by FarzadKarkhani**

### CODE REVIEW

**Comment by michaelryancaputo** [comment]
Hey there,
The checked attribute is actually assigned to optional. The ternary returns true/false. Your change would make the attribute show up as:
checked="checked" or checked=""

I dont think this is what you meant to do.

**Comment by FarzadKarkhani** [comment]
Hi,
Yes, you are right, but I think checked attribute isn't assigned to DOM elements?

**Comment by michaelryancaputo** [comment]
React will render any of these as "checked":
`<input type="checkbox" checked />`
`<input type="checkbox" checked="true" />`


What actual problem are you trying to solve with this?

**Comment by FarzadKarkhani** [comment]
I have a problem with `input[type=checkbox]:checked` in my css rules. when I inspect with developer tools there isn't `checked` attr in rendered element.

**Pull request closed without merging**
