### PR TITLE
Added checkAll and uncheckAll functions

### PR DESCRIPTION
**Pull request by colino**
Hi,
react-checkbox-group is very useful. I needed these two functionalities and I added them.

### CODE REVIEW

**Comment by ziad-saab** [comment]
Hello @colino and thanks. I'm not sure it's safe to uncheck all the boxes on mount and on update. Sometimes the component is instantiated with pre-checked boxes. I can see how the `checkAll` and `uncheckAll` methods could be useful, but I'm not too sure about the additional stuff in the lifecycle hooks.

Can you please explain what you were trying to accomplish with these additions?

**Comment by colino** [comment]
Hi,
in my use case i must give the possibility to users to start with all boxes unchecked becouse users must add selections and not to uncheck them to have selected result set. CheckAll and UncheckAll are handy features to select all or none. For example if an user checks wrong boxes he need to clean all. What do you think?

Date: Wed, 21 Oct 2015 08:40:07 -0700

**Comment by ziad-saab** [comment]
@colino again I think that the methods themselves can be useful, but what about calling them from cDM and cDU? I think this part should be removed. What do you think?

**Comment by ziad-saab** [comment]
@colino I have released version 1.0.0 of this library, which aims to fix all sorts of issues people were having with it. Please try it out and let me know what you think :)

**Pull request closed without merging**
