### PR TITLE
Updated CheckboxGroup to match react-radio-group API

### PR DESCRIPTION
**Pull request by ziad-saab**
@NoNeedToBail can you please review this and let me know what you think?

I've updated the test cases and they're all passing.

### CODE REVIEW

**Comment by ziad-saab** [comment]
Still need to update the README examples

**Comment by NoNeedToBail** [comment]
Sure thing, taking a look now.

**Comment by ziad-saab** [comment]
@NoNeedToBail I caught a bug for the controlled component case. I forgot to implement `componentWillReceiveProps`. i'm going to add a test and make it work :)

**Comment by NoNeedToBail** [comment]
Just one thought: while the concept of a single radio button is nonsensical, the same is not true of a single checkbox - and right now it blows up if you render a Checkbox without a CheckboxGroup.

It's worth considering either making context-dependent behaviour optional or throwing a clear error (rather than 'Cannot read property 'name' of undefined') in the case that a Checkbox is rendered without a parent CheckboxGroup.

**Comment by ziad-saab** [comment]
@NoNeedToBail I'm adding a `throw` to `componentWillMount` and getting the following in my console now. What do you think? Is it clear enough?

screen shot 2016-08-05 at 00 25 30

**Comment by NoNeedToBail** [comment]
Yeah, I think that's much clearer. :+1:

**Comment by ziad-saab** [comment]
OK. I'll update the version number, rebase, merge the PR and publish it on NPM.

**Comment by NoNeedToBail** [comment]
Sounds great. I'll update to the new version at work tomorrow if I get a chance and let you know if I run into any issues.

**Pull request merged**
